<Button>
	font_name: 'SIXTY.TTF'
	font_size: 30

<Calc>
	quest_screen: quest_screen
	answer_screen: answer_screen
	GridLayout:
		cols: 1
		size: root.width, root.height
		GridLayout:
			cols: 1
			size: root.width, 1
			size_hint: 1, .5
			Label:
				id: quest_screen
				font_size: 30
				multiline: False
				font_name: 'Roboto-Light.ttf'
			Label:
				id: answer_screen
				font_size: 30
				font_name: 'Roboto-Light.ttf'
		GridLayout:
			cols: 4
			Button:
				text: 'OFF'
				on_press: root.pop()
			Button:
				id: btnON
				text: 'ON'
				on_press: root.ON_()
			Button:
				id: btnDEL
				text: 'DEL'
				on_press: root.DEL_()
			Button:
				id: btnDIV
				text: '÷'
				on_press: root.operator(btnDIV)
				font_name: 'Roboto-Regular.ttf'
				
			Button:
				id: btn7
				text: '7'
				on_press: root.solve(btn7)
			Button:
				id: btn8
				text: '8'
				on_press: root.solve(btn8)
			Button:
				id: btn9
				text: '9'
				on_press: root.solve(btn9)
			Button:
				id: btnMUL
				text: '×'
				on_press: root.operator(btnMUL)
				font_name: 'Roboto-Regular.ttf'
				
			Button:
				id: btn4
				text: '4'
				on_press: root.solve(btn4)
			Button:
				id: btn5
				text: '5'
				on_press: root.solve(btn5)
			Button:
				id: btn6
				text: '6'
				on_press: root.solve(btn6)
			Button:
				id: btnSUB
				text: '-'
				on_press: root.operator(btnSUB)
				font_name: 'Roboto-Regular.ttf'
				
			Button:
				id: btn1
				text: '1'
				on_press: root.solve(btn1)
			Button:
				id: btn2
				text: '2'
				on_press: root.solve(btn2)
			Button:
				id: btn3
				text: '3'
				on_press: root.solve(btn3)
			Button:
				id: btnADD
				text: '+'
				on_press: root.operator(btnADD)
				font_name: 'Roboto-Regular.ttf'
				
			Button:
				id: btn0
				text: '0'
				on_press: root.solve(btn0)
			Button:
				id: btnDEC
				text: '.'
				on_press: root.solve(btnDEC)
			Button:
				id: btnANS
				text: 'Ans'
				on_press: root.ANS_()
			Button:
				id: btnEQUAL
				text: '='
				on_press: root.EQUAL_()
				font_name: 'Roboto-Regular.ttf'
			
<Exit>
	id: exit
	title: 'Are You Sure You Want To Quit?'
	size_hint: .9, .2
	GridLayout:
		cols: 2
		Button:
			text: 'Cancel'
			color: 1, 1, 1, 1
			background_color: 0, 0, 0, 0
			on_press: exit.dismiss()
		Button:
			text: 'Exit'
			color: 1, 0, 0, 1
			background_color: 0, 0, 0, 0
			on_press: app.stop()
					
		